### ISSUE TITLE
Have you figured out this.

### ISSUE THREAD

**Issue by enyachoke** [HawiCaesar/pay_confirmation#1]
Am trying to figure out this but the mpesa documenation is crap.

**Comment by HawiCaesar** [comment]
Hi enyachoke

I am still trying to figure it out. I made a java web project but I am still trying to bring all the pieces of the documentation together, still far away

**Comment by barmao** [comment]
@enyachoke if you are a huge fan of the web you can try this solution too : https://github.com/kn9ts/project-mulla

@HawiCaesar waiting for the documentation too.

**Comment by HawiCaesar** [comment]
@enyachoke , @barmao Hope you have seen the new M-PESA API.

**Comment by barmao** [comment]
@HawiCaesar yes, thanks man.
